"use strict";

module.exports = {
  CrearInvitacion: 1 << 0,
  Expulsar: 1 << 1,
  Banear: 1 << 2,
  Administrador: 1 << 3,
  GestionarCanales: 1 << 4,
  GestionarServidor: 1 << 5,
  AñadirReacciones: 1 << 6,
  VerRegistroDeAuditoria: 1 << 7,
  PrioridadAlHablar: 1 << 8,
  Transmitir: 1 << 9,
  VerCanal: 1 << 10,
  EnviarMensajes: 1 << 11,
  EnviarMensajesTTS: 1 << 12,
  GestionarMensajes: 1 << 13,
  Embeds: 1 << 14,
  AdjuntarArchivos: 1 << 15,
  VerHistorialDeMensajes: 1 << 16,
  MencionarEveryone: 1 << 17,
  UsarEmojisExternos: 1 << 18,
  VerInformacionDelServidor: 1 << 19,
  Conectar: 1 << 20,
  Hablar: 1 << 21,
  SilenciarMiembros: 1 << 22,
  EnsordecerMiembros: 1 << 23,
  MoverMiembros: 1 << 24,
  UsarVAD: 1 << 25,
  CambiarApodo: 1 << 26,
  GestionarApodos: 1 << 27,
  GestionarRoles: 1 << 28,
  GestionarWebhooks: 1 << 29,
  GestionarEmojis: 1 << 30,
  UsarComandosDeBarra: 1 << 31,
  SolicitarHablar: 1 << 32,
  GestionarHilos: 1 << 34,
  CrearHilosPublicos: 1 << 35,
  CrearHilosPrivados: 1 << 36,
  UsarEmojisExternos: 1 << 37,
  EnviarMensajesEnHilos: 1 << 38,
  InciarActividadesEmbed: 1 << 39,
  ModerarMiembros: 1 << 40,
};
